# -*- coding: utf-8 -*-
"""Churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13NohKopanWAXnT02RhsgOsGy3X96T7jf
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Churn_dataset.csv')
df.head()

df.drop('customerID', axis=1, inplace=True)
df.info()

#df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
#df = df[df["TotalCharges"].notnull()]
df['TotalCharges']=df['TotalCharges'].replace({' ':'0.0'}).astype(float)

"""#Exploratory Data Analysis (EDA)

##Numerical Column Analysis
"""

df.describe()

df['SeniorCitizen'].unique()

df['SeniorCitizen'] = df['SeniorCitizen'].replace({1: 'Yes', 0: 'No'}).astype('object')
df['SeniorCitizen'].unique()

numeric_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']

def plot_histograms(df, cols):
    fig, axes = plt.subplots(1, 3, figsize=(15, 4))
    for i, col in enumerate(cols):
        sns.histplot(df[col], kde=True, ax=axes[i])
        axes[i].set_title(f'Distribution of {col}')

        col_mean = df[col].mean()
        col_median = df[col].median()

        axes[i].axvline(col_mean, color='r', linestyle='--', label='Mean')
        axes[i].axvline(col_median, color='g', linestyle='-', label='Median')
        axes[i].legend()
    plt.tight_layout()
    plt.show()


def plot_boxplots(df, cols):
    fig, axes = plt.subplots(1, 3, figsize=(15, 4))
    for i, col in enumerate(cols):
        axes[i].set_title(f'Distribution of {col}')
        sns.boxplot(y=df[col], ax=axes[i])
        axes[i].set_ylabel(col)
    plt.tight_layout()
    plt.show()

plot_histograms(df, numeric_cols)
plot_boxplots(df, numeric_cols)

plt.figure(figsize=(10, 6))
plt.title('Correlation Matrix')
sns.heatmap(df[numeric_cols].corr(), annot=True, cmap='Blues')
plt.show()

"""##Categorical Column Analysis"""

catergorical_cols = [col for col in df.columns if col not in numeric_cols and col not in ['Churn']]
catergorical_cols

fig, axes = plt.subplots(4, 4, figsize=(16, 16))
axes = axes.flatten()

#df[catergorical_cols] = df[catergorical_cols].apply(lambda x: x.replace('No internet service', 'No'))
#df[catergorical_cols] = df[catergorical_cols].apply(lambda x: x.replace('No phone service', 'No'))

for i, col in enumerate(catergorical_cols):
    if i < 16:
        sns.countplot(x=col, data=df, ax=axes[i])
        axes[i].set_title(f'Distribution of {col}')
plt.tight_layout()
plt.show()

catergorical_cols

from sklearn.preprocessing import LabelEncoder
import pickle

encoder = {}
for col in catergorical_cols:
  lc = LabelEncoder()
  df[col] = lc.fit_transform(df[col])
  encoder[col] = lc

plt.figure(figsize=(10, 6))
plt.title('Correlation Matrix')
sns.heatmap(df[catergorical_cols].corr(), annot=True, cmap='Blues')
plt.show()

"""#Model generation

##Train and test split
"""

pd.set_option('future.no_silent_downcasting', True)
df['Churn'] = df['Churn'].replace({'Yes': 1, 'No': 0}).astype(int)
df['Churn'].unique()

x = df.drop(columns=['Churn'])
y = df['Churn']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

print(y_train.value_counts())

from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
x_train_smote, y_train_smote = smote.fit_resample(x_train, y_train)

print(y_train_smote.value_counts())

"""##Model Training"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier

models = {
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(random_state=42),
    'XGBoost': XGBClassifier(random_state=42),
    'Random Forest': RandomForestClassifier(random_state=42),
}

from sklearn.model_selection import cross_val_score

cv_scores = {}

for model_name, model in models.items():
    cv_scores[model_name] = cross_val_score(model, x_train_smote, y_train_smote, cv=5, scoring='accuracy').mean()
    print(f'{model_name} CV Score: {cv_scores[model_name]:.2f}')
print()
cv_scores

"""##Model Evaluation"""

best_model = models[max(cv_scores, key=cv_scores.get)]
print(f'Best Model: {best_model}')

best_model.fit(x_train_smote, y_train_smote)
y_test_pred = best_model.predict(x_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_test_pred)

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

print(classification_report(y_test, y_test_pred))

plt.figure(figsize=(6,4))
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')

sns.heatmap(confusion_matrix(y_test, y_test_pred), annot=True, fmt='d', cmap='Blues')
plt.show()

model_data = {
    "model": best_model,
    "encoder": encoder
}

with open('churn_model.pkl', 'wb') as f:
    pickle.dump(model_data, f)

"""#Load and Predict Model"""

with open('churn_model.pkl', 'rb') as f:
    model = pickle.load(f)

loaded_model = model["model"]
loaded_encoder = model["encoder"]

loaded_encoder

input_data = {
    "gender": "Male",
    "SeniorCitizen": "No",
    "Partner": "No",
    "Dependents": "No",
    "tenure": 2,
    "PhoneService": "Yes",
    "MultipleLines": "No",
    "InternetService": "DSL",
    "OnlineSecurity": "Yes",
    "OnlineBackup": "Yes",
    "DeviceProtection": "No",
    "TechSupport": "No",
    "StreamingTV": "No",
    "StreamingMovies": "No",
    "Contract": "Month-to-month",
    "PaperlessBilling": "Yes",
    "PaymentMethod": "Mailed check",
    "MonthlyCharges": 53.85,
    "TotalCharges": 108.15
}

ip_df = pd.DataFrame([input_data])
for col, encoder in loaded_encoder.items():
  ip_df[col] = encoder.transform(ip_df[col])

print("Yes") if loaded_model.predict(ip_df)[0] == 1 else print("No")
print(f'Prediction Probability: {loaded_model.predict_proba(ip_df)}')